name: haskell-godaddy
version: 0.0.0.6
synopsis: "Command-line interface and library to configure Godaddy domain records"
github: "ibizaman/haskell-godaddy"
license: BSD3
license-file: LICENSE
author: "Pierre Penninckx"
maintainer: "ibizapeanut@gmail.com"
copyright: "2020 Pierre Penninckx"
category: DNS,Executable,Godaddy

description: Please see the README on GitHub at <https://github.com/ibizaman/haskell-godaddy#readme>

dependencies:
    # base must match what comes with ghc
    - base == 4.14.1.0
    - aeson == 1.5.*
    - exceptions
    - http-client == 0.6.*
    - http-client-tls == 0.3.5.*
    - http-types == 0.12.*
    - text == 1.2.*
    - time == 1.9.*
    - servant-server == 0.18.*
    - servant-client == 0.18.*

default-extensions:
    - OverloadedStrings

library:
    source-dirs: src
    dependencies: {}

executables:
    haskell-godaddy-exe:
        main: main.hs
        source-dirs: app
        dependencies:
            - haskell-godaddy
            - config-ini == 0.2.*
            - envy == 2.1.*
            - optparse-applicative == 0.15.*
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

tests:
    haskell-godaddy-test:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - haskell-godaddy
            - hspec == 2.7.*
            - hspec-core == 2.7.*
            - hspec-discover == 2.7.*
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-incomplete-uni-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-overlapping-patterns
    - -fwarn-tabs
    - -fwarn-unused-imports
